const CREATE_NEW_USER = "CREATE_NEW_USER"
const DELETE_USER = "DELETE_USER"
const USER_INFO = "USER_INFO"
const CHANGE_INFO = "CHANGE_INFO"


export {CREATE_NEW_USER, DELETE_USER, USER_INFO, CHANGE_INFO}; 